import { describe, it, expect } from "vitest";
import { exportToMarkdown } from "./export-markdown";
import type { ExportData } from "./export-json";
import type { CrossReview, SynthesisResponse } from "@llmtium/core";
import type { SerializedWorkflowResult } from "./serialize";

function makeReview(overrides?: Partial<CrossReview>): CrossReview {
  return {
    scores: {
      "Response A": { correctness: 4, completeness: 3, actionability: 5, clarity: 4 },
      "Response B": { correctness: 3, completeness: 4, actionability: 3, clarity: 5 },
    },
    issues: ["Lacks error handling details"],
    disagreements: [
      {
        topic: "Database choice",
        a: { response_id: "Response A", quote: "Use PostgreSQL" },
        b: { response_id: "Response B", quote: "Use SQLite" },
        assessment: "PostgreSQL is better for production",
        suggested_resolution: "Go with PostgreSQL",
      },
    ],
    missing_info: ["Deployment strategy"],
    confidence: 0.85,
    confidence_reason: "Mostly aligned",
    ...overrides,
  };
}

function makeSynthesis(overrides?: Partial<SynthesisResponse>): SynthesisResponse {
  return {
    output: "The synthesized recommendation is to use PostgreSQL with a phased rollout.",
    resolved_disagreements: [
      {
        topic: "Database choice",
        chosen_position: "PostgreSQL",
        rationale: "Better scalability for production",
        supporting_responses: ["Response A"],
      },
    ],
    open_questions: ["What is the expected query volume?"],
    action_items: [
      { priority: "P0", item: "Set up PostgreSQL cluster" },
      { priority: "P1", item: "Write migration scripts" },
      { priority: "P2", item: "Update documentation" },
    ],
    confidence: 0.92,
    confidence_reason: "Strong consensus with minor gaps",
    ...overrides,
  };
}

function makeFixture(overrides?: Partial<ExportData>): ExportData {
  const review = makeReview();
  const synthesis = makeSynthesis();

  const result: SerializedWorkflowResult = {
    status: "success",
    input: {
      prompt: "Review my deployment plan",
      workflow: "review_plan",
      models: ["anthropic", "openai"],
      synthesizer: "anthropic",
    },
    stages: {
      drafts: {},
      reviews: {},
      synthesis,
      mapping: { "Response A": "anthropic", "Response B": "openai" },
    },
    errors: [{ stage: "draft", model: "google", error: "Rate limit exceeded" }],
    telemetry: {
      totalDurationMs: 8500,
      stageDurationMs: { draft: 3200, review: 4100, synthesis: 1200 },
      draftTokens: {
        anthropic: { tokensIn: 150, tokensOut: 420 },
        openai: { tokensIn: 130, tokensOut: 380 },
      },
    },
    pipeline: {
      status: "success",
      drafts: {},
      reviews: {},
      synthesis,
      mapping: { "Response A": "anthropic", "Response B": "openai" },
      errors: [{ stage: "draft", model: "google", error: "Rate limit exceeded" }],
      telemetry: {
        totalDurationMs: 8500,
        stageDurationMs: { draft: 3200, review: 4100, synthesis: 1200 },
        draftTokens: {
          anthropic: { tokensIn: 150, tokensOut: 420 },
          openai: { tokensIn: 130, tokensOut: 380 },
        },
      },
    },
  };

  return {
    prompt: "Review my deployment plan",
    models: ["anthropic", "openai"],
    synthesizer: "anthropic",
    drafts: {
      anthropic: "Deploy to AWS ECS with blue-green strategy.",
      openai: "Use Kubernetes with rolling updates.",
    },
    reviews: { anthropic: review, openai: makeReview() },
    synthesis,
    mapping: { "Response A": "anthropic", "Response B": "openai" },
    result,
    errors: [{ stage: "draft", model: "google", error: "Rate limit exceeded" }],
    ...overrides,
  };
}

describe("exportToMarkdown", () => {
  it("should contain header with generator string", () => {
    const md = exportToMarkdown(makeFixture());
    expect(md).toContain("Generated by LLMtium \u2014 Multi-LLM Deliberation Tool");
  });

  it("should contain original prompt text", () => {
    const md = exportToMarkdown(makeFixture());
    expect(md).toContain("Review my deployment plan");
  });

  it("should contain each model's draft with de-anonymized names", () => {
    const md = exportToMarkdown(makeFixture());
    expect(md).toContain("### Anthropic");
    expect(md).toContain("Deploy to AWS ECS with blue-green strategy.");
    expect(md).toContain("### OpenAI");
    expect(md).toContain("Use Kubernetes with rolling updates.");
  });

  it("should contain cross-review scores table with de-anonymized labels", () => {
    const md = exportToMarkdown(makeFixture());
    // Score table should have de-anonymized response labels
    expect(md).toContain("Anthropic");
    expect(md).toContain("OpenAI");
    // Should contain score values
    expect(md).toMatch(/\|\s*4\s*\|\s*3\s*\|\s*5\s*\|\s*4\s*\|/);
  });

  it("should contain disagreements with de-anonymized names and assessment", () => {
    const md = exportToMarkdown(makeFixture());
    expect(md).toContain("Database choice");
    expect(md).toContain("Anthropic");
    expect(md).toContain("Use PostgreSQL");
    expect(md).toContain("OpenAI");
    expect(md).toContain("Use SQLite");
    expect(md).toContain("PostgreSQL is better for production");
  });

  it("should contain synthesis output text and confidence", () => {
    const md = exportToMarkdown(makeFixture());
    expect(md).toContain("The synthesized recommendation is to use PostgreSQL with a phased rollout.");
    expect(md).toContain("0.92");
  });

  it("should contain resolved disagreements, open questions, and action items", () => {
    const md = exportToMarkdown(makeFixture());
    // Resolved disagreements
    expect(md).toContain("PostgreSQL");
    expect(md).toContain("Better scalability for production");
    // Open questions
    expect(md).toContain("What is the expected query volume?");
    // Action items with priorities
    expect(md).toContain("[P0]");
    expect(md).toContain("Set up PostgreSQL cluster");
    expect(md).toContain("[P1]");
    expect(md).toContain("Write migration scripts");
    expect(md).toContain("[P2]");
    expect(md).toContain("Update documentation");
  });

  it("should contain token usage table with per-model and total counts", () => {
    const md = exportToMarkdown(makeFixture());
    // Per-model tokens
    expect(md).toContain("150");
    expect(md).toContain("420");
    expect(md).toContain("130");
    expect(md).toContain("380");
    // Total
    expect(md).toContain("280");
    expect(md).toContain("800");
  });

  it("should have sections in correct order", () => {
    const md = exportToMarkdown(makeFixture());
    const promptIdx = md.indexOf("## Prompt");
    const draftsIdx = md.indexOf("## Drafts");
    const reviewsIdx = md.indexOf("## Cross-Reviews");
    const synthesisIdx = md.indexOf("## Synthesis");
    const telemetryIdx = md.indexOf("## Telemetry");
    const errorsIdx = md.indexOf("## Errors");

    expect(promptIdx).toBeLessThan(draftsIdx);
    expect(draftsIdx).toBeLessThan(reviewsIdx);
    expect(reviewsIdx).toBeLessThan(synthesisIdx);
    expect(synthesisIdx).toBeLessThan(telemetryIdx);
    expect(telemetryIdx).toBeLessThan(errorsIdx);
  });

  it("should contain error details with stage, model, and error message", () => {
    const md = exportToMarkdown(makeFixture());
    expect(md).toContain("draft");
    expect(md).toContain("google");
    expect(md).toContain("Rate limit exceeded");
  });

  it("should use raw labels when mapping is null", () => {
    const md = exportToMarkdown(makeFixture({ mapping: null }));
    // Should not crash, should use raw labels like "Response A"
    expect(md).toContain("Response A");
    expect(md).toContain("Response B");
  });

  it("should show 'No errors.' when errors array is empty", () => {
    const md = exportToMarkdown(makeFixture({ errors: [] }));
    expect(md).toContain("No errors.");
  });
});
