import { PROVIDER_META } from "./provider-meta";
import type { ExportData } from "./export-json";
import type { CrossReview, PipelineError, PipelineTelemetry } from "@llmtium/core";

function resolveLabel(label: string, mapping: Record<string, string> | null): string {
  if (!mapping) return label;
  const modelId = mapping[label];
  if (!modelId) return label;
  return PROVIDER_META[modelId]?.name ?? modelId;
}

function modelName(modelId: string): string {
  return PROVIDER_META[modelId]?.name ?? modelId;
}

function formatMs(ms: number): string {
  return `${(ms / 1000).toFixed(1)}s`;
}

function formatHeader(): string {
  return [
    "# LLMtium Deliberation Report",
    "",
    "> Generated by LLMtium \u2014 Multi-LLM Deliberation Tool",
    `> Exported: ${new Date().toISOString()}`,
    "",
  ].join("\n");
}

function formatPrompt(prompt: string): string {
  return ["## Prompt", "", prompt, ""].join("\n");
}

function formatDrafts(
  models: string[],
  drafts: Record<string, string>,
  telemetry: PipelineTelemetry,
): string {
  const lines = ["## Drafts", ""];

  for (const modelId of models) {
    const draft = drafts[modelId];
    if (!draft) continue;

    lines.push(`### ${modelName(modelId)}`, "");
    lines.push(draft, "");

    const tokens = telemetry.draftTokens[modelId];
    if (tokens) {
      lines.push(`*Tokens: ${tokens.tokensIn} in / ${tokens.tokensOut} out*`, "");
    }
  }

  return lines.join("\n");
}

function formatReviews(
  reviews: Record<string, CrossReview>,
  mapping: Record<string, string> | null,
): string {
  const entries = Object.entries(reviews);
  if (entries.length === 0) return "";

  const lines = ["## Cross-Reviews", ""];

  for (const [reviewerId, review] of entries) {
    lines.push(`### Review by ${modelName(reviewerId)} (confidence: ${Number(review.confidence).toFixed(2)})`, "");

    // Scores table
    if (review.scores.length > 0) {
      lines.push("#### Scores", "");
      lines.push("| Response | Corr | Comp | Action | Clarity |");
      lines.push("|----------|------|------|--------|---------|");
      for (const s of review.scores) {
        const name = resolveLabel(s.response_id, mapping);
        lines.push(`| ${name} | ${Number(s.correctness)} | ${Number(s.completeness)} | ${Number(s.actionability)} | ${Number(s.clarity)} |`);
      }
      lines.push("");
    }

    // Disagreements
    if (review.disagreements.length > 0) {
      lines.push("#### Disagreements", "");
      for (const d of review.disagreements) {
        const aName = resolveLabel(d.a.response_id, mapping);
        const bName = resolveLabel(d.b.response_id, mapping);
        lines.push(`- **${d.topic}**: ${aName} ("${d.a.quote}") vs ${bName} ("${d.b.quote}") \u2014 ${d.assessment}`);
        if (d.suggested_resolution) {
          lines.push(`  - *Resolution:* ${d.suggested_resolution}`);
        }
      }
      lines.push("");
    }

    // Issues
    if (review.issues.length > 0) {
      lines.push("#### Issues", "");
      for (const issue of review.issues) {
        lines.push(`- ${issue}`);
      }
      lines.push("");
    }

    // Missing info
    if (review.missing_info.length > 0) {
      lines.push("#### Missing Info", "");
      for (const info of review.missing_info) {
        lines.push(`- ${info}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

function formatSynthesis(
  data: ExportData,
): string {
  const { synthesis, mapping } = data;
  const lines = [`## Synthesis (confidence: ${Number(synthesis.confidence).toFixed(2)})`, ""];

  lines.push(synthesis.output, "");

  // Resolved disagreements
  if (synthesis.resolved_disagreements.length > 0) {
    lines.push("### Resolved Disagreements", "");
    for (const d of synthesis.resolved_disagreements) {
      const supporters = d.supporting_responses
        .map((label) => resolveLabel(label, mapping))
        .join(", ");
      lines.push(`- **${d.topic}**: ${d.chosen_position} \u2014 ${d.rationale} (supported by: ${supporters})`);
    }
    lines.push("");
  }

  // Open questions
  if (synthesis.open_questions.length > 0) {
    lines.push("### Open Questions", "");
    for (const q of synthesis.open_questions) {
      lines.push(`- ${q}`);
    }
    lines.push("");
  }

  // Action items
  if (synthesis.action_items.length > 0) {
    lines.push("### Action Items", "");
    for (const item of synthesis.action_items) {
      lines.push(`- [${item.priority}] ${item.item}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function formatTelemetry(telemetry: PipelineTelemetry): string {
  const lines = ["## Telemetry", ""];

  lines.push(`- Total duration: ${formatMs(telemetry.totalDurationMs)}`);
  lines.push(
    `- Draft: ${formatMs(telemetry.stageDurationMs.draft)} | Review: ${formatMs(telemetry.stageDurationMs.review)} | Synthesis: ${formatMs(telemetry.stageDurationMs.synthesis)}`,
  );
  lines.push("");

  // Token usage table
  const tokenEntries = Object.entries(telemetry.draftTokens);
  if (tokenEntries.length > 0) {
    lines.push("### Token Usage", "");
    lines.push("| Model | Tokens In | Tokens Out |");
    lines.push("|-------|-----------|------------|");

    let totalIn = 0;
    let totalOut = 0;
    for (const [modelId, tokens] of tokenEntries) {
      totalIn += tokens.tokensIn;
      totalOut += tokens.tokensOut;
      lines.push(`| ${modelName(modelId)} | ${tokens.tokensIn} | ${tokens.tokensOut} |`);
    }
    lines.push(`| **Total** | ${totalIn} | ${totalOut} |`);
    lines.push("");
  }

  return lines.join("\n");
}

function formatErrors(errors: PipelineError[]): string {
  const lines = ["## Errors", ""];

  if (errors.length === 0) {
    lines.push("No errors.");
  } else {
    for (const err of errors) {
      lines.push(`- [${err.stage}] ${err.model}: ${err.error}`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

export function exportToMarkdown(data: ExportData): string {
  const telemetry = data.result.telemetry;

  return [
    formatHeader(),
    formatPrompt(data.prompt),
    formatDrafts(data.models, data.drafts, telemetry),
    formatReviews(data.reviews, data.mapping),
    formatSynthesis(data),
    formatTelemetry(telemetry),
    formatErrors(data.errors),
  ].join("\n");
}
